<a href="https://colab.research.google.com/github/Shrutipython123/Bank-Churn-Project/blob/main/Demo_mnist_convnet_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,Dropout
import numpy as np


In [ ]:
mnist=keras.datasets.mnist

In [ ]:
mnist.load_data()

In [ ]:
keras.datasets.mnist.load_data()

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [ ]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [ ]:
# Print the shapes of the arrays
print("Train images shape:", x_train.shape)   # (60000, 28, 28)
print("Train labels shape:", y_train.shape)   # (60000,)
print("Test images shape:", x_test.shape)     # (10000, 28, 28)
print("Test labels shape:", y_test.shape)     # (10000,)

Train images shape: (60000, 28, 28)
Train labels shape: (60000,)
Test images shape: (10000, 28, 28)
Test labels shape: (10000,)


In [ ]:
# scale images to the [0,1] range
x_train=x_train.astype("float32")/255
x_test=x_test.astype("float32")/255

In [ ]:
#make sure images gave shape(28,28,1)
x_train=np.expand_dims(x_train,-1)
x_test=np.expand_dims(x_test,-1)
print("x_train_shape",x_train.shape)
print("x_test_shape",x_test.shape)

x_train_shape (60000, 28, 28, 1)
x_test_shape (10000, 28, 28, 1)


In [ ]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
# covert class vectors to binary class matrices
y_train=keras.utils.to_categorical(y_train,10)
y_test=keras.utils.to_categorical(y_test,10)
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
y_train.shape

(60000, 10)

In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
mnist_model=Sequential()

In [ ]:
mnist_model.add(Conv2D(32,kernel_size=(3,3),activation="relu",input_shape=(28,28,1)))
mnist_model.add(MaxPooling2D(pool_size=(2,2)))
mnist_model.add(Conv2D(64,kernel_size=(3,3),activation="relu"))
mnist_model.add(MaxPooling2D(pool_size=(2,2)))
mnist_model.add(Flatten())
mnist_model.add(Dropout(0.5))
mnist_model.add(Dense(10,activation="softmax"))




In [ ]:
mnist_model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_10 (Conv2D)          (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 13, 13, 32)       0         
 2D)                                                             
                                                                 
 conv2d_11 (Conv2D)          (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_9 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_4 (Flatten)         (None, 1600)              0         
                                                                 
 dropout_3 (Dropout)         (None, 1600)             

In [ ]:
mnist_model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
y_train.shape

(60000, 10)

In [ ]:
mnist_model.fit(x_train, y_train, batch_size=128, epochs=15, validation_split=0.1)

Epoch 1/15
422/422 [==============================] - 51s 119ms/step - loss: 0.3594 - accuracy: 0.8895 - val_loss: 0.0793 - val_accuracy: 0.9800
Epoch 2/15
422/422 [==============================] - 47s 113ms/step - loss: 0.1136 - accuracy: 0.9650 - val_loss: 0.0576 - val_accuracy: 0.9853
Epoch 3/15
422/422 [==============================] - 48s 114ms/step - loss: 0.0854 - accuracy: 0.9735 - val_loss: 0.0495 - val_accuracy: 0.9872
Epoch 4/15
422/422 [==============================] - 48s 115ms/step - loss: 0.0727 - accuracy: 0.9781 - val_loss: 0.0428 - val_accuracy: 0.9882
Epoch 5/15
422/422 [==============================] - 47s 111ms/step - loss: 0.0642 - accuracy: 0.9801 - val_loss: 0.0383 - val_accuracy: 0.9912
Epoch 6/15
422/422 [==============================] - 48s 114ms/step - loss: 0.0567 - accuracy: 0.9819 - val_loss: 0.0382 - val_accuracy: 0.9895
Epoch 7/15
422/422 [==============================] - 48s 115ms/step - loss: 0.0539 - accuracy: 0.9834 - val_loss: 0.0341 - val_ac

In [ ]:
score = mnist_model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.023511895909905434
Test accuracy: 0.9918000102043152
